import os

from pathlib import Path

from app.application.use_cases import IngestDocument
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from app.infra.db.ormmodels import Organization as OrganizationORM
from app.infra.db.implementations import PostgreSQL_OrganizationRepository, PostgreSQL_DocumentRepository, PostgreSQL_ChunkRepository
from app.infra.storage.implementations import Local_DocumentStorage
from app.infra.parser.implementations import V1_PDFParser
from app.application.services import V1_Chunker
from app.domain.entities import Organization

from dotenv import load_dotenv
load_dotenv()


'''
In order to test the use case we must create the necessary conditions for it to run, like in the endpoint. 
We need:
- Connect to a test database
- Create a new test organization in the database
- Create instances of the repositories, parser, chunker and storage. We should be careful when using the storage, as it can write files to disk. We can use a temporary directory for that and clean it up after the test.
- Create an instance of the use case. 
- Execute the use case with a sample file and check results. We can use a sample PDF file for that, which we can create programmatically or use a fixture.

- We can test succesful outcomes as well as error conditions.
'''

def test_ingest_document():
    # Create a database connection. We assume the database and its tables are already created and accessible.
    
    user = os.environ["DB_USER"]
    password = os.environ["DB_PASSWORD"]
    host = os.environ["DB_HOST"]
    port = os.environ["DB_PORT"]
    test_db_name = os.environ["DB_TEST_NAME"]    
    DATABASE_URL = f"postgresql+psycopg://{user}:{password}@{host}:{port}/{test_db_name}"
    
    engine = create_engine(DATABASE_URL, pool_pre_ping=True)
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine, expire_on_commit=False, future=True)    
    db = SessionLocal()
    
    try:    
        # instantiate organization repo:
        org_repo = PostgreSQL_OrganizationRepository(db)
        
        # create a test organization with the implementation of the port:
        entity_org = Organization(name="Test Organization") #the id is autogenerated
        
        org_repo.add(entity_org)
        print(entity_org.id)
        
        assert entity_org.id is not None
        assert entity_org.id == org_repo.get_by_id(entity_org.id).id
        assert entity_org.id == org_repo.get_by_name(entity_org.name).id
        
        #Prepare the use case dependencies. repo, storage, parser, chunker. org_repo is already created.
        
        doc_repo = PostgreSQL_DocumentRepository(db)
        chunk_repo = PostgreSQL_ChunkRepository(db)
        
        # Storage. We will use a temporary directory for testing and clean it up after the test.
        temp_storage_path = "./temp_test_storage"
        if not os.path.exists(temp_storage_path):
            os.makedirs(temp_storage_path)
        storage = Local_DocumentStorage(temp_storage_path)
        
        #parser. use the original
        parser = V1_PDFParser()
        
        #chunker, the original
        chunker = V1_Chunker()
        
        # Instantiate the use case with the dependencies
        use_case = IngestDocument(
            org_repo = org_repo,
            doc_repo = doc_repo,   
            chunk_repo = chunk_repo,   
            storage = storage,
            parser = parser,
            chunker = chunker
        )
        
        #we will use a pdf already stored in ./samples/pdf-sample-test.pdf
        filename = "pdf-sample-test.pdf"
        with open(f"./samples/{filename}", "rb") as f:
            file_content = f.read() 
                        
        # Execute the use case
        result = use_case.execute(entity_org.id, file_content, filename)
        
        assert result.organization_id == entity_org.id
        assert result.document_id is not None
        assert result.chunks_created > 0
        assert result.document_hash is not None
        
        doc = doc_repo.get_by_id(entity_org.id, result.document_id)
        assert doc is not None
        assert doc.title == filename
        assert doc.source_type == "pdf"
        assert f"nisl blandit. Integer lacinia ante ac libero lobortis imperdiet. Nullam mollis convallis ipsum," in doc.content
        
        print(result.chunks_created)
        chunks = chunk_repo.get_by_document(entity_org.id, result.document_id)
        assert len(chunks) == result.chunks_created
        print(doc.content[-3000:])
        assert any(f"Integer lacinia ante ac libero lobortis imperdiet" in c.content for c in chunks)
        
    
        

        
        
        
        
    finally:
        
        #delete the storage files created during the test
        try:
            storage.delete(entity_org.id, result.document_id)
        except Exception as e:
            print(f"Failed to clean up storage file: {str(e)}")
        
        #also delete the organization folder if it's empty
        org_dir = Path(temp_storage_path) / str(result.organization_id)
        try:
            os.rmdir(org_dir)
        except OSError:
            pass
        
        db.rollback()
        db.close()