import hashlib
import os

from pathlib import Path
import uuid

import pytest

from app.application.use_cases import IngestDocument
from app.infra import db
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from app.domain.entities import Document

from app.infra.db.ormmodels import Organization as OrganizationORM
from app.infra.db.implementations import PostgreSQL_OrganizationRepository, PostgreSQL_DocumentRepository, PostgreSQL_ChunkRepository
from app.infra.storage.implementations import Local_DocumentStorage
from app.infra.parser.implementations import V1_PDFParser
from app.application.services import V1_Chunker
from app.domain.entities import Organization

from app.application.exceptions import (
    ChunkPersistenceError,
    OrganizationNotFoundError,
    DocumentPersistError,
    UseCaseError,
    DocumentAlreadyExistsError,
    IngestDocumentError,
    EmptyFileError,
    UnsupportedFileTypeError,
    StorageDeleteError, 
    StorageWriteError, 
    ParsingError,
    ChunkingError,
    PersistenceError
)

from dotenv import load_dotenv
load_dotenv()


def make_db_session():
    user = os.environ["DB_USER"]
    password = os.environ["DB_PASSWORD"]
    host = os.environ["DB_HOST"]
    port = os.environ["DB_PORT"]
    test_db_name = os.environ["DB_TEST_NAME"]
    DATABASE_URL = f"postgresql+psycopg://{user}:{password}@{host}:{port}/{test_db_name}"

    engine = create_engine(DATABASE_URL, pool_pre_ping=True)
    SessionLocal = sessionmaker(
        autocommit=False,
        autoflush=False,
        bind=engine,
        expire_on_commit=False,
        future=True,
    )
    return SessionLocal()

def read_sample_pdf_bytes():
    filename = "pdf-sample-test.pdf"
    with open(f"./samples/{filename}", "rb") as f:
        return filename, f.read()
    
def build_use_case(db, path_storage, doc_repo=None, storage=None, chunker=None, chunk_repo=None):
    if storage is None:
        storage = Local_DocumentStorage(path_storage)
    org_repo = PostgreSQL_OrganizationRepository(db)
    if doc_repo is None:
        doc_repo = PostgreSQL_DocumentRepository(db)
    if chunk_repo is None:
        chunk_repo = PostgreSQL_ChunkRepository(db)
    parser = V1_PDFParser()
    if chunker is None:
        chunker = V1_Chunker()

    return IngestDocument(
        org_repo=org_repo,
        doc_repo=doc_repo,
        chunk_repo=chunk_repo,
        storage=storage,
        parser=parser,
        chunker=chunker,
    ), org_repo


'''
In order to test the use case we must create the necessary conditions for it to run, like in the endpoint. 
We need:
- Connect to a test database
- Create a new test organization in the database
- Create instances of the repositories, parser, chunker and storage. We should be careful when using the storage, as it can write files to disk. We can use a temporary directory for that and clean it up after the test.
- Create an instance of the use case. 
- Execute the use case with a sample file and check results. We can use a sample PDF file for that, which we can create programmatically or use a fixture.

- We can test succesful outcomes as well as error conditions.
'''

'''
tmp_path is a pytest fixture that provides a temporary directory unique to the test invocation, which is automatically cleaned up after the test function finishes. This is ideal for testing file storage without affecting the actual filesystem or needing manual cleanup.
'''
def test_ingest_document(tmp_path):
    
    # Create a database connection. We assume the database and its tables are already created and accessible.   
    db = make_db_session()    
    result = None
    storage = None
    entity_org = None
        
    try:    
        # Instantiate the use case with the dependencies
        use_case, org_repo = build_use_case(db, str(tmp_path))
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        #we use a pdf already stored in ./samples/pdf-sample-test.pdf
        filename, file_content = read_sample_pdf_bytes()
        
        # Execute the use case
        result = use_case.execute(entity_org.id, file_content, filename)
        
        assert result.organization_id == entity_org.id
        assert result.document_id is not None
        assert result.chunks_created > 0
        assert result.document_hash is not None
        
        doc = use_case.doc_repo.get_by_id(entity_org.id, result.document_id)
        assert doc is not None
        assert doc.title == filename
        assert doc.source_type == "pdf"
        assert f"nisl blandit. Integer lacinia ante ac libero lobortis imperdiet. Nullam mollis convallis ipsum," in doc.content
        
        #print(result.chunks_created)
        chunks = use_case.chunk_repo.get_by_document(entity_org.id, result.document_id)
        assert len(chunks) == result.chunks_created
        #print(doc.content[-3000:])
        joined = " ".join(c.content for c in chunks)       
        for word in ["Integer", "lacinia", "ante", "ac", "libero", "lobortis", "imperdiet", "Vestibulum", "mollis", "convallis", "ipsum"]:
            assert word in joined
        
    finally:
        db.rollback()
        db.close()

def test_empty_file(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:    
        use_case, org_repo = build_use_case(db, str(tmp_path))
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename = "empty.pdf"
        file_content = b""
        
        with pytest.raises(EmptyFileError): 
            use_case.execute(entity_org.id, file_content, filename)            
    finally:
        db.rollback()
        db.close()

def test_org_not_found(tmp_path):
    db = make_db_session()    
    result = None
        
    try:    
        use_case, org_repo = build_use_case(db, str(tmp_path))
        
        non_existent_org_id = "00000000-0000-0000-0000-000000000000"
        filename, file_content = read_sample_pdf_bytes()
        
        with pytest.raises(OrganizationNotFoundError):
            use_case.execute(non_existent_org_id, file_content, filename)
            
    finally:
        db.rollback()
        db.close()

def test_parsing_error(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:    
        use_case, org_repo = build_use_case(db, str(tmp_path))
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename = "not_a_pdf.txt"
        file_content = b"This is not a PDF file."
        
        with pytest.raises(ParsingError):
            use_case.execute(entity_org.id, file_content, filename)
            
    finally:
        db.rollback()
        db.close()

def test_empty_pdf(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:    
        use_case, org_repo = build_use_case(db, str(tmp_path))
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename = "empty.pdf"
        file_content = b"%PDF-1.4\n%EOF"  # Minimal PDF structure with no content        
        with pytest.raises(ParsingError):
            use_case.execute(entity_org.id, file_content, filename)
            
    finally:
        db.rollback()
        db.close()

def test_document_already_exists_hash(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:    
        use_case, org_repo = build_use_case(db, str(tmp_path))
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename, file_content = read_sample_pdf_bytes()
        
        # First ingestion should succeed
        result1 = use_case.execute(entity_org.id, file_content, filename)
        assert result1.document_id is not None
        
        # Second ingestion with the same file should raise DocumentAlreadyExistsError
        with pytest.raises(DocumentAlreadyExistsError):
            use_case.execute(entity_org.id, file_content, filename)
            
    finally:
        db.rollback()
        db.close()

def test_persistence_error(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:           
        #we fake the document repo.        
        class failingDocumentRepo:         
            def add(self, document: Document) -> None:
                raise Exception("Simulated database failure")            
            def get_by_hash(self, organization_id: uuid.UUID, document_hash: str) -> Document | None:                
                return None        
        
        use_case, org_repo = build_use_case(db, str(tmp_path), doc_repo=failingDocumentRepo())
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename, file_content = read_sample_pdf_bytes()
        
        with pytest.raises(DocumentPersistError):
            use_case.execute(entity_org.id, file_content, filename) 
        
    finally:
        db.rollback()
        db.close()

def test_storage_error(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:           
        #we fake the storage.        
        class failingStorage:         
            def save(self, organization_id: uuid.UUID, document_id: uuid.UUID, content: bytes) -> None:
                raise Exception("Simulated storage failure")     
        
        use_case, org_repo = build_use_case(db, str(tmp_path), storage=failingStorage())
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename, file_content = read_sample_pdf_bytes()
        
        with pytest.raises(StorageWriteError):
            use_case.execute(entity_org.id, file_content, filename)
    finally:
        db.rollback()
        db.close()
        
        
def test_chunk_error(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:           
        #we fake the chunker.        
        class failingChunker:         
            def chunk_text(self, organization_id: uuid.UUID, document_id: uuid.UUID, content: str):
                raise Exception("Simulated chunking failure")     
        
        use_case, org_repo = build_use_case(db, str(tmp_path), chunker=failingChunker())
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename, file_content = read_sample_pdf_bytes()
        
        with pytest.raises(ChunkingError):
            use_case.execute(entity_org.id, file_content, filename)
    finally:
        db.rollback()
        db.close()

def test_chunkrepo_error(tmp_path):
    db = make_db_session()    
    result = None
    entity_org = None
        
    try:           
        #we fake the chunker.        
        class failingChunkerRepo:         
            def add_many(self, chunks) -> None:
                raise Exception("Simulated chunking failure")     
        
        use_case, org_repo = build_use_case(db, str(tmp_path), chunk_repo=failingChunkerRepo())
        
        # create a test organization
        entity_org = Organization(name="Test Organization") #the id is autogenerated        
        org_repo.add(entity_org)
        
        filename, file_content = read_sample_pdf_bytes()
        
        with pytest.raises(ChunkPersistenceError):
            use_case.execute(entity_org.id, file_content, filename)
    finally:
        db.rollback()
        db.close()